# Generated by Django 3.2.12 on 2023-04-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
