# Generated by Django 3.2.12 on 2023-04-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230419_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listadecompras',
            name='produtos',
        ),
        migrations.DeleteModel(
            name='ItemDeCompra',
        ),
        migrations.DeleteModel(
            name='ListaDeCompras',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
