# Generated by Django 3.2.12 on 2023-04-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='data',
        ),
        migrations.AddField(
            model_name='compra',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
