# Generated by Django 3.2.12 on 2023-04-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230413_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
