# Generated by Django 3.2.12 on 2023-04-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_compras'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compras',
            new_name='Compra',
        ),
    ]
