# Generated by Django 4.1.7 on 2023-04-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_listacompras'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListaCompras',
        ),
    ]
