# Generated by Django 3.2.12 on 2023-04-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_listacompras'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
